import CrossCheckDrawingData

/-! Session 5, targets 1 and 5: kernel checks of the drawings, part 4 of 4 (generated by `tools/export_drawing.py`; see `CrossCheckDrawing.lean`). -/

namespace Homm3.DrawingData

open Homm3 Homm3.Embed Homm3.LemmaData

set_option profiler true
set_option profiler.threshold 50

theorem va02 : d02.check q02 C02 = true := by decide +kernel
theorem eq02 : SameBoard d02 q02 C02 l02 k02 := by decide +kernel

theorem va08 : d08.check q08 C08 = true := by decide +kernel
theorem eq08 : SameBoard d08 q08 C08 l08 k08 := by decide +kernel

theorem va11 : d11.check q11 C11 = true := by decide +kernel
theorem eq11 : SameBoard d11 q11 C11 l11 k11 := by decide +kernel

theorem va12 : d12.check q12 C12 = true := by decide +kernel
theorem eq12 : SameBoard d12 q12 C12 l12 k12 := by decide +kernel

theorem va17 : d17.check q17 C17 = true := by decide +kernel
theorem eq17 : SameBoard d17 q17 C17 l17 k17 := by decide +kernel

theorem va21 : d21.check q21 C21 = true := by decide +kernel
theorem eq21 : SameBoard d21 q21 C21 l21 k21 := by decide +kernel

theorem va25 : d25.check q25 C25 = true := by decide +kernel
theorem eq25 : SameBoard d25 q25 C25 l25 k25 := by decide +kernel

theorem va31 : d31.check q31 C31 = true := by decide +kernel
theorem eq31 : SameBoard d31 q31 C31 l31 k31 := by decide +kernel

theorem va34 : d34.check q34 C34 = true := by decide +kernel
theorem eq34 : SameBoard d34 q34 C34 l34 k34 := by decide +kernel

theorem va37 : d37.check q37 C37 = true := by decide +kernel
theorem eq37 : SameBoard d37 q37 C37 l37 k37 := by decide +kernel

theorem va42 : d42.check q42 C42 = true := by decide +kernel
theorem eq42 : SameBoard d42 q42 C42 l42 k42 := by decide +kernel

end Homm3.DrawingData
