import CrossCheckDrawingData

/-! Session 5, targets 1 and 5: kernel checks of the drawings, part 1 of 4 (generated by `tools/export_drawing.py`; see `CrossCheckDrawing.lean`). -/

namespace Homm3.DrawingData

open Homm3 Homm3.Embed Homm3.LemmaData

set_option profiler true
set_option profiler.threshold 50

theorem va03 : d03.check q03 C03 = true := by decide +kernel
theorem eq03 : SameBoard d03 q03 C03 l03 k03 := by decide +kernel

theorem va04 : d04.check q04 C04 = true := by decide +kernel
theorem eq04 : SameBoard d04 q04 C04 l04 k04 := by decide +kernel

theorem va07 : d07.check q07 C07 = true := by decide +kernel
theorem eq07 : SameBoard d07 q07 C07 l07 k07 := by decide +kernel

theorem va10 : d10.check q10 C10 = true := by decide +kernel
theorem eq10 : SameBoard d10 q10 C10 l10 k10 := by decide +kernel

theorem va15 : d15.check q15 C15 = true := by decide +kernel
theorem eq15 : SameBoard d15 q15 C15 l15 k15 := by decide +kernel

theorem va20 : d20.check q20 C20 = true := by decide +kernel
theorem eq20 : SameBoard d20 q20 C20 l20 k20 := by decide +kernel

theorem va22 : d22.check q22 C22 = true := by decide +kernel
theorem eq22 : SameBoard d22 q22 C22 l22 k22 := by decide +kernel

theorem va32 : d32.check q32 C32 = true := by decide +kernel
theorem eq32 : SameBoard d32 q32 C32 l32 k32 := by decide +kernel

theorem va36 : d36.check q36 C36 = true := by decide +kernel
theorem eq36 : SameBoard d36 q36 C36 l36 k36 := by decide +kernel

theorem va40 : d40.check q40 C40 = true := by decide +kernel
theorem eq40 : SameBoard d40 q40 C40 l40 k40 := by decide +kernel

theorem va43 : d43.check q43 C43 = true := by decide +kernel
theorem eq43 : SameBoard d43 q43 C43 l43 k43 := by decide +kernel

end Homm3.DrawingData
