import CrossCheckLemmaData

/-! Session 4, target 5: kernel checks of the Lemma D.4 boards, part 1 of 4 (generated by `tools/export_lemma.py`; see `CrossCheckLemma.lean`). -/

namespace Homm3.LemmaData

open Homm3 BoardData T3

set_option profiler true
set_option profiler.threshold 50

theorem ck04 : l04.check q04 C04 = true := by decide +kernel
theorem cv04 : coverCheck q04 C04 = true := by decide +kernel
theorem yes04 : YesV l04 q04 C04 := yes_of ck04 cv04

theorem ck05 : l05.check q05 C05 = true := by decide +kernel
theorem cv05 : coverCheck q05 C05 = true := by decide +kernel
theorem yes05 : YesV l05 q05 C05 := yes_of ck05 cv05

theorem ck06 : l06.check q06 C06 = true := by decide +kernel
theorem cv06 : coverCheck q06 C06 = true := by decide +kernel
theorem yes06 : YesV l06 q06 C06 := yes_of ck06 cv06

theorem ck08 : l08.check q08 C08 = true := by decide +kernel
theorem cv08 : coverCheck q08 C08 = true := by decide +kernel
theorem yes08 : YesV l08 q08 C08 := yes_of ck08 cv08

theorem ck12 : l12.check q12 C12 = true := by decide +kernel
theorem cv12 : coverCheck q12 C12 = false := by decide +kernel
theorem no12 : NoV l12 q12 C12 := no_of ck12 cv12

theorem ck21 : l21.check q21 C21 = true := by decide +kernel
theorem cv21 : coverCheck q21 C21 = false := by decide +kernel
theorem no21 : NoV l21 q21 C21 := no_of ck21 cv21

theorem ck23 : l23.check q23 C23 = true := by decide +kernel
theorem cv23 : coverCheck q23 C23 = false := by decide +kernel
theorem no23 : NoV l23 q23 C23 := no_of ck23 cv23

theorem ck28 : l28.check q28 C28 = true := by decide +kernel
theorem cv28 : coverCheck q28 C28 = true := by decide +kernel
theorem yes28 : YesV l28 q28 C28 := yes_of ck28 cv28

theorem ck29 : l29.check q29 C29 = true := by decide +kernel
theorem cv29 : coverCheck q29 C29 = true := by decide +kernel
theorem yes29 : YesV l29 q29 C29 := yes_of ck29 cv29

theorem ck32 : l32.check q32 C32 = true := by decide +kernel
theorem cv32 : coverCheck q32 C32 = true := by decide +kernel
theorem yes32 : YesV l32 q32 C32 := yes_of ck32 cv32

theorem ck39 : l39.check q39 C39 = true := by decide +kernel
theorem cv39 : coverCheck q39 C39 = true := by decide +kernel
theorem yes39 : YesV l39 q39 C39 := yes_of ck39 cv39

end Homm3.LemmaData
