import CrossCheckDrawingData

/-! Session 5, targets 1 and 5: kernel checks of the drawings, part 2 of 4 (generated by `tools/export_drawing.py`; see `CrossCheckDrawing.lean`). -/

namespace Homm3.DrawingData

open Homm3 Homm3.Embed Homm3.LemmaData

set_option profiler true
set_option profiler.threshold 50

theorem va00 : d00.check q00 C00 = true := by decide +kernel
theorem eq00 : SameBoard d00 q00 C00 l00 k00 := by decide +kernel

theorem va01 : d01.check q01 C01 = true := by decide +kernel
theorem eq01 : SameBoard d01 q01 C01 l01 k01 := by decide +kernel

theorem va06 : d06.check q06 C06 = true := by decide +kernel
theorem eq06 : SameBoard d06 q06 C06 l06 k06 := by decide +kernel

theorem va13 : d13.check q13 C13 = true := by decide +kernel
theorem eq13 : SameBoard d13 q13 C13 l13 k13 := by decide +kernel

theorem va14 : d14.check q14 C14 = true := by decide +kernel
theorem eq14 : SameBoard d14 q14 C14 l14 k14 := by decide +kernel

theorem va19 : d19.check q19 C19 = true := by decide +kernel
theorem eq19 : SameBoard d19 q19 C19 l19 k19 := by decide +kernel

theorem va23 : d23.check q23 C23 = true := by decide +kernel
theorem eq23 : SameBoard d23 q23 C23 l23 k23 := by decide +kernel

theorem va26 : d26.check q26 C26 = true := by decide +kernel
theorem eq26 : SameBoard d26 q26 C26 l26 k26 := by decide +kernel

theorem va27 : d27.check q27 C27 = true := by decide +kernel
theorem eq27 : SameBoard d27 q27 C27 l27 k27 := by decide +kernel

theorem va30 : d30.check q30 C30 = true := by decide +kernel
theorem eq30 : SameBoard d30 q30 C30 l30 k30 := by decide +kernel

theorem va38 : d38.check q38 C38 = true := by decide +kernel
theorem eq38 : SameBoard d38 q38 C38 l38 k38 := by decide +kernel

theorem va39 : d39.check q39 C39 = true := by decide +kernel
theorem eq39 : SameBoard d39 q39 C39 l39 k39 := by decide +kernel

end Homm3.DrawingData
