import CrossCheckLemmaData

/-! Session 4, target 5: kernel checks of the Lemma D.4 boards, part 4 of 4 (generated by `tools/export_lemma.py`; see `CrossCheckLemma.lean`). -/

namespace Homm3.LemmaData

open Homm3 BoardData T3

set_option profiler true
set_option profiler.threshold 50

theorem ck01 : l01.check q01 C01 = true := by decide +kernel
theorem cv01 : coverCheck q01 C01 = true := by decide +kernel
theorem yes01 : YesV l01 q01 C01 := yes_of ck01 cv01

theorem ck02 : l02.check q02 C02 = true := by decide +kernel
theorem cv02 : coverCheck q02 C02 = true := by decide +kernel
theorem yes02 : YesV l02 q02 C02 := yes_of ck02 cv02

theorem ck03 : l03.check q03 C03 = true := by decide +kernel
theorem cv03 : coverCheck q03 C03 = true := by decide +kernel
theorem yes03 : YesV l03 q03 C03 := yes_of ck03 cv03

theorem ck11 : l11.check q11 C11 = true := by decide +kernel
theorem cv11 : coverCheck q11 C11 = true := by decide +kernel
theorem yes11 : YesV l11 q11 C11 := yes_of ck11 cv11

theorem ck16 : l16.check q16 C16 = true := by decide +kernel
theorem cv16 : coverCheck q16 C16 = true := by decide +kernel
theorem yes16 : YesV l16 q16 C16 := yes_of ck16 cv16

theorem ck20 : l20.check q20 C20 = true := by decide +kernel
theorem cv20 : coverCheck q20 C20 = false := by decide +kernel
theorem no20 : NoV l20 q20 C20 := no_of ck20 cv20

theorem ck27 : l27.check q27 C27 = true := by decide +kernel
theorem cv27 : coverCheck q27 C27 = true := by decide +kernel
theorem yes27 : YesV l27 q27 C27 := yes_of ck27 cv27

theorem ck31 : l31.check q31 C31 = true := by decide +kernel
theorem cv31 : coverCheck q31 C31 = true := by decide +kernel
theorem yes31 : YesV l31 q31 C31 := yes_of ck31 cv31

theorem ck34 : l34.check q34 C34 = true := by decide +kernel
theorem cv34 : coverCheck q34 C34 = true := by decide +kernel
theorem yes34 : YesV l34 q34 C34 := yes_of ck34 cv34

theorem ck37 : l37.check q37 C37 = true := by decide +kernel
theorem cv37 : coverCheck q37 C37 = false := by decide +kernel
theorem no37 : NoV l37 q37 C37 := no_of ck37 cv37

theorem ck41 : l41.check q41 C41 = true := by decide +kernel
theorem cv41 : coverCheck q41 C41 = true := by decide +kernel
theorem yes41 : YesV l41 q41 C41 := yes_of ck41 cv41

end Homm3.LemmaData
