import CrossCheckDrawingData

/-! Session 5, targets 1 and 5: kernel checks of the drawings, part 3 of 4 (generated by `tools/export_drawing.py`; see `CrossCheckDrawing.lean`). -/

namespace Homm3.DrawingData

open Homm3 Homm3.Embed Homm3.LemmaData

set_option profiler true
set_option profiler.threshold 50

theorem va05 : d05.check q05 C05 = true := by decide +kernel
theorem eq05 : SameBoard d05 q05 C05 l05 k05 := by decide +kernel

theorem va09 : d09.check q09 C09 = true := by decide +kernel
theorem eq09 : SameBoard d09 q09 C09 l09 k09 := by decide +kernel

theorem va16 : d16.check q16 C16 = true := by decide +kernel
theorem eq16 : SameBoard d16 q16 C16 l16 k16 := by decide +kernel

theorem va18 : d18.check q18 C18 = true := by decide +kernel
theorem eq18 : SameBoard d18 q18 C18 l18 k18 := by decide +kernel

theorem va24 : d24.check q24 C24 = true := by decide +kernel
theorem eq24 : SameBoard d24 q24 C24 l24 k24 := by decide +kernel

theorem va28 : d28.check q28 C28 = true := by decide +kernel
theorem eq28 : SameBoard d28 q28 C28 l28 k28 := by decide +kernel

theorem va29 : d29.check q29 C29 = true := by decide +kernel
theorem eq29 : SameBoard d29 q29 C29 l29 k29 := by decide +kernel

theorem va33 : d33.check q33 C33 = true := by decide +kernel
theorem eq33 : SameBoard d33 q33 C33 l33 k33 := by decide +kernel

theorem va35 : d35.check q35 C35 = true := by decide +kernel
theorem eq35 : SameBoard d35 q35 C35 l35 k35 := by decide +kernel

theorem va41 : d41.check q41 C41 = true := by decide +kernel
theorem eq41 : SameBoard d41 q41 C41 l41 k41 := by decide +kernel

end Homm3.DrawingData
