import CrossCheckLemmaData

/-! Session 4, target 5: kernel checks of the Lemma D.4 boards, part 3 of 4 (generated by `tools/export_lemma.py`; see `CrossCheckLemma.lean`). -/

namespace Homm3.LemmaData

open Homm3 BoardData T3

set_option profiler true
set_option profiler.threshold 50

theorem ck07 : l07.check q07 C07 = true := by decide +kernel
theorem cv07 : coverCheck q07 C07 = true := by decide +kernel
theorem yes07 : YesV l07 q07 C07 := yes_of ck07 cv07

theorem ck13 : l13.check q13 C13 = true := by decide +kernel
theorem cv13 : coverCheck q13 C13 = true := by decide +kernel
theorem yes13 : YesV l13 q13 C13 := yes_of ck13 cv13

theorem ck15 : l15.check q15 C15 = true := by decide +kernel
theorem cv15 : coverCheck q15 C15 = false := by decide +kernel
theorem no15 : NoV l15 q15 C15 := no_of ck15 cv15

theorem ck17 : l17.check q17 C17 = true := by decide +kernel
theorem cv17 : coverCheck q17 C17 = true := by decide +kernel
theorem yes17 : YesV l17 q17 C17 := yes_of ck17 cv17

theorem ck19 : l19.check q19 C19 = true := by decide +kernel
theorem cv19 : coverCheck q19 C19 = false := by decide +kernel
theorem no19 : NoV l19 q19 C19 := no_of ck19 cv19

theorem ck24 : l24.check q24 C24 = true := by decide +kernel
theorem cv24 : coverCheck q24 C24 = true := by decide +kernel
theorem yes24 : YesV l24 q24 C24 := yes_of ck24 cv24

theorem ck25 : l25.check q25 C25 = true := by decide +kernel
theorem cv25 : coverCheck q25 C25 = true := by decide +kernel
theorem yes25 : YesV l25 q25 C25 := yes_of ck25 cv25

theorem ck33 : l33.check q33 C33 = true := by decide +kernel
theorem cv33 : coverCheck q33 C33 = true := by decide +kernel
theorem yes33 : YesV l33 q33 C33 := yes_of ck33 cv33

theorem ck35 : l35.check q35 C35 = true := by decide +kernel
theorem cv35 : coverCheck q35 C35 = false := by decide +kernel
theorem no35 : NoV l35 q35 C35 := no_of ck35 cv35

theorem ck40 : l40.check q40 C40 = true := by decide +kernel
theorem cv40 : coverCheck q40 C40 = true := by decide +kernel
theorem yes40 : YesV l40 q40 C40 := yes_of ck40 cv40

theorem ck43 : l43.check q43 C43 = true := by decide +kernel
theorem cv43 : coverCheck q43 C43 = true := by decide +kernel
theorem yes43 : YesV l43 q43 C43 := yes_of ck43 cv43

end Homm3.LemmaData
