import CrossCheckLemmaData

/-! Session 4, target 5: kernel checks of the Lemma D.4 boards, part 2 of 4 (generated by `tools/export_lemma.py`; see `CrossCheckLemma.lean`). -/

namespace Homm3.LemmaData

open Homm3 BoardData T3

set_option profiler true
set_option profiler.threshold 50

theorem ck00 : l00.check q00 C00 = true := by decide +kernel
theorem cv00 : coverCheck q00 C00 = true := by decide +kernel
theorem yes00 : YesV l00 q00 C00 := yes_of ck00 cv00

theorem ck09 : l09.check q09 C09 = true := by decide +kernel
theorem cv09 : coverCheck q09 C09 = true := by decide +kernel
theorem yes09 : YesV l09 q09 C09 := yes_of ck09 cv09

theorem ck10 : l10.check q10 C10 = true := by decide +kernel
theorem cv10 : coverCheck q10 C10 = true := by decide +kernel
theorem yes10 : YesV l10 q10 C10 := yes_of ck10 cv10

theorem ck14 : l14.check q14 C14 = true := by decide +kernel
theorem cv14 : coverCheck q14 C14 = false := by decide +kernel
theorem no14 : NoV l14 q14 C14 := no_of ck14 cv14

theorem ck18 : l18.check q18 C18 = true := by decide +kernel
theorem cv18 : coverCheck q18 C18 = false := by decide +kernel
theorem no18 : NoV l18 q18 C18 := no_of ck18 cv18

theorem ck22 : l22.check q22 C22 = true := by decide +kernel
theorem cv22 : coverCheck q22 C22 = true := by decide +kernel
theorem yes22 : YesV l22 q22 C22 := yes_of ck22 cv22

theorem ck26 : l26.check q26 C26 = true := by decide +kernel
theorem cv26 : coverCheck q26 C26 = true := by decide +kernel
theorem yes26 : YesV l26 q26 C26 := yes_of ck26 cv26

theorem ck30 : l30.check q30 C30 = true := by decide +kernel
theorem cv30 : coverCheck q30 C30 = true := by decide +kernel
theorem yes30 : YesV l30 q30 C30 := yes_of ck30 cv30

theorem ck36 : l36.check q36 C36 = true := by decide +kernel
theorem cv36 : coverCheck q36 C36 = false := by decide +kernel
theorem no36 : NoV l36 q36 C36 := no_of ck36 cv36

theorem ck38 : l38.check q38 C38 = true := by decide +kernel
theorem cv38 : coverCheck q38 C38 = false := by decide +kernel
theorem no38 : NoV l38 q38 C38 := no_of ck38 cv38

theorem ck42 : l42.check q42 C42 = true := by decide +kernel
theorem cv42 : coverCheck q42 C42 = true := by decide +kernel
theorem yes42 : YesV l42 q42 C42 := yes_of ck42 cv42

end Homm3.LemmaData
