import Homm3.Hex
import Homm3.Damage
import Homm3.Knapsack
import Homm3.KnapsackArray
import Homm3.Corridor
import Homm3.Battle
import Homm3.BattleFacts
import Homm3.CorridorGame
import Homm3.Prop11
import Homm3.Prop11Lower
import Homm3.Theorem1
import Homm3.HexGraph
import Homm3.MatchingReach
import Homm3.Prop11General
import Homm3.Health
import Homm3.Exec
import Homm3.Certificate
import Homm3.ExecExamples
import Homm3.ThreePartition
import Homm3.Accounting
import Homm3.Theorem2
import Homm3.Walk
import Homm3.Theorem4
import Homm3.LemmaE20
import Homm3.X3C
import Homm3.X3CBoard
import Homm3.Theorem3
import Homm3.BoardCheck
import Homm3.Gadgets
import Homm3.EmbedGeom
import Homm3.Embed
import Homm3.EmbedCheck
import Homm3.Step0
import Homm3.Step1
import Homm3.Axioms
