#!/usr/bin/env python3
"""Export the boards of Lemma D.4's construction (`homm3/scripts/embed_lemma.py`) as Lean data.

Session 4, target 5 (the literal part).  `verify_embedding.corpus()` is the deduplicated corpus
of every published suite (61 families); `build_board_lemma` turns each into either a board
(45 families) or `G_no` (16: an element lies in no set).  For every board this script records
Python's verdicts (`x3c_is_yes`, `check_geometry` empty) and writes it in the packed format of
`BoardData.ofPacked`: `k` free cells, each a 44-bit record `i*2^24 + label*2^16 + dist`
(`i = x + W*y`; label 0 < e + 1 < 128 for element e, 128 + g for the enemy hex of member g;
dist = BFS distance from the deployment hex inside the region), lowest record first.

Both modules import the scripts read-only; nothing under `homm3/` is written.

Output: `CrossCheckLemmaData.lean`, the check modules `CrossCheckLemmaA`–`D.lean` (balanced by
board area, so lake checks them in parallel), the umbrella `CrossCheckLemma.lean` and a JSON
summary on stdout.  `--only I` writes just board I, for timing.

Run from formal/lean:  PYTHONDONTWRITEBYTECODE=1 python3 tools/export_lemma.py
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from collections import deque

HERE = os.path.dirname(os.path.abspath(__file__))
LEAN_ROOT = os.path.dirname(HERE)
SCRIPTS = os.path.normpath(os.path.join(LEAN_ROOT, "..", "..", "scripts"))  # artifact root/scripts
sys.path.insert(0, SCRIPTS)
sys.dont_write_bytecode = True

import verify_x3c as V  # noqa: E402
import verify_embedding as VE  # noqa: E402
from embed_lemma import build_board_lemma  # noqa: E402


PARTS = 4


def pack(inst):
    W, H = inst["width"], inst["height"]
    owner = inst["owner"]
    code = {}
    for h, (kind, idx) in owner.items():
        c = idx + 1 if kind == "e" else 128 + idx
        assert 0 < c < 256
        code[h] = c
    dist = {}
    for e, p in inst["deploy"].items():
        dist[p] = 0
        dq = deque([p])
        while dq:
            cur = dq.popleft()
            for n in V._neighbours(W, H, cur):
                if owner.get(n) == ("e", e) and n not in dist:
                    dist[n] = dist[cur] + 1
                    dq.append(n)
    region = [h for h, o in owner.items() if o[0] == "e"]
    assert all(h in dist for h in region), "region hex unreachable from its deployment hex"
    cells = 0
    order = sorted(owner)
    for j, h in enumerate(order):
        d = dist.get(h, 0)
        assert h < 2 ** 20 and d < 2 ** 16
        cells |= (h * 2 ** 24 + code[h] * 2 ** 16 + d) << (44 * j)
    n_el = inst["n_elements"]
    p = [(inst["deploy"][e] % W, inst["deploy"][e] // W) for e in range(n_el)]
    z = [(inst["enemy_hex"][s] % W, inst["enemy_hex"][s] // W) for s in range(len(inst["sets"]))]
    return {"W": W, "H": H, "k": len(order), "cells": cells, "p": p, "z": z, "sigma": W * H,
            "q": n_el // 3, "CL": [list(s) for s in inst["sets"]]}


def lean_board(name, b):
    pairs = lambda xs: "[" + ", ".join(f"({x}, {y})" for x, y in xs) + "]"
    return (f"def {name} : BoardData :=\n"
            f"  .ofPacked {b['W']} {b['H']} {b['k']}\n"
            f"    0x{b['cells']:x}\n"
            f"    {pairs(b['p'])}\n    {pairs(b['z'])} {b['sigma']}\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", type=int, default=None)
    args = ap.parse_args()
    t0 = time.time()
    fams = VE.corpus()
    boards, gno = [], []
    for fi, (n, sets) in enumerate(fams):
        kind, inst = build_board_lemma(n, sets)
        x3c = V.x3c_is_yes(n, sets)
        if kind != "board":
            assert not x3c, "G_no for a yes-instance"
            gno.append({"family": fi, "n": n, "C": [list(s) for s in sets],
                        "reason": inst.get("reason", "")})
            continue
        geo = V.check_geometry(inst)
        assert not geo, geo
        b = pack(inst)
        b["family"], b["x3c"] = fi, x3c
        b["free"] = b["k"]
        boards.append(b)
    sel = list(range(len(boards))) if args.only is None else [args.only]

    data = ["import Homm3.BoardCheck", "",
            "/-!", "# Session 4, target 5. The boards of Lemma D.4's construction, as data", "",
            "Generated by `tools/export_lemma.py` from `homm3/scripts/embed_lemma.py`",
            "(`build_board_lemma` over `verify_embedding.corpus()`, read-only imports).  `lNN` is",
            "the `NN`-th family of the corpus that yields a board (the rest yield `G_no`), in the",
            "packed format of `BoardData.ofPacked`.  Do not edit by hand.",
            "-/", "", "namespace Homm3.LemmaData", "", "open Homm3", ""]
    for i in sel:
        b = boards[i]
        data.append(lean_board(f"l{i:02d}", b))
        data.append(f"def q{i:02d} : ℕ := {b['q']}")
        data.append(f"def C{i:02d} : List (List ℕ) := {b['CL']}")
        data.append("")
    data += ["end Homm3.LemmaData", ""]
    with open(os.path.join(LEAN_ROOT, "CrossCheckLemmaData.lean"), "w") as f:
        f.write("\n".join(data))

    # the kernel checks one module on one core: split the checks into PARTS modules balanced by
    # board area (the checker's cost is linear in W*H), which lake builds in parallel
    parts = [[] for _ in range(PARTS)]
    load = [0] * PARTS
    for i in sorted(sel, key=lambda i: -boards[i]["W"] * boards[i]["H"]):
        m = load.index(min(load))
        parts[m].append(i)
        load[m] += boards[i]["W"] * boards[i]["H"]
    names = []
    for m, part in enumerate(parts):
        if not part:
            continue
        name = f"CrossCheckLemma{'ABCDEFGH'[m]}"
        names.append(name)
        chk = ["import CrossCheckLemmaData", "",
               f"/-! Session 4, target 5: kernel checks of the Lemma D.4 boards, part {m + 1} of "
               f"{PARTS} (generated by `tools/export_lemma.py`; see `CrossCheckLemma.lean`). -/",
               "", "namespace Homm3.LemmaData", "", "open Homm3 BoardData T3", "",
               "set_option profiler true", "set_option profiler.threshold 50", ""]
        for i in sorted(part):
            b = boards[i]
            v = "true" if b["x3c"] else "false"
            chk.append(f"theorem ck{i:02d} : l{i:02d}.check q{i:02d} C{i:02d} = true := by decide +kernel")
            chk.append(f"theorem cv{i:02d} : coverCheck q{i:02d} C{i:02d} = {v} := by decide +kernel")
            if b["x3c"]:
                chk.append(f"theorem yes{i:02d} : YesV l{i:02d} q{i:02d} C{i:02d} := yes_of ck{i:02d} cv{i:02d}")
            else:
                chk.append(f"theorem no{i:02d} : NoV l{i:02d} q{i:02d} C{i:02d} := no_of ck{i:02d} cv{i:02d}")
            chk.append("")
        chk += ["end Homm3.LemmaData", ""]
        with open(os.path.join(LEAN_ROOT, name + ".lean"), "w") as f:
            f.write("\n".join(chk))

    top = [f"import {n}" for n in names] + ["",
           "/-!",
           "# Session 4, target 5. Theorem 3 on the boards of Lemma D.4's construction", "",
           "Every board that `embed_lemma.build_board_lemma` builds from the corpus of",
           "`verify_embedding.py` (44 of 61 families; the other 17 are `G_no`: an element lies in",
           "no set), **in the kernel**: `ckNN` — the board passes `BoardData.check`, so (I1)–(I4)",
           "hold (`check_sound`) and `theorem3` applies; `cvNN` — exact cover by `coverCheck`;",
           "`yesNN` / `noNN` — the game verdict through `theorem3` at both constant sets,",
           "Corollary 3.1, and uniqueness of the all-ones allocation on yes-boards.  The Python",
           "artifact plays the game only on the smallest of these boards; here every board gets",
           "its verdict, because the invariants are checked and `theorem3` does the rest.  This is",
           "Lemma D.4 **on this corpus**, not the lemma itself (which is universal over planar",
           "incidence graphs; see PROGRESS.md, session 4).  The checks live in",
           ", ".join(f"`{n}`" for n in names) + " (split for parallel builds).",
           "-/", "", "namespace Homm3.LemmaData", "", "open Homm3 BoardData", ""]
    for i in sel:
        top.append(f"#print axioms {'yes' if boards[i]['x3c'] else 'no'}{i:02d}")
    top += ["", "end Homm3.LemmaData", ""]
    with open(os.path.join(LEAN_ROOT, "CrossCheckLemma.lean"), "w") as f:
        f.write("\n".join(top))

    summary = [{"i": i, "family": b["family"], "q": b["q"], "sets": len(b["CL"]), "W": b["W"],
                "H": b["H"], "free": b["free"], "x3c": b["x3c"]} for i, b in enumerate(boards)]
    print(json.dumps({"boards": summary, "gno": gno, "secs": round(time.time() - t0, 1)}))


if __name__ == "__main__":
    main()
